version: "3.8"

services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
      - '80:80'
    volumes:
      - ./Track-Issue-JS:/usr/local/apache2/htdocs
    networks:
      - app-network

  node:
    image: node:14
    container_name: ts-compiler
    working_dir: /app
    volumes:
      - ./Track-Issue-JS:/app
    command: bash -c "npm install && npm run build"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge